# Read me


Following notebook assumes all downloads of literature search are presented at path `../../data/wos` in .xls form with column naming as provided by Web of Science platform

## Output of this notebook:

- `../../data/partitions`: Raw data that is to be screened is provided in a single `.csv` and their splits into 5 partitions in `.xlsx` form. 
This includes serves are the base raw data over which screening and coding will be applied. 

- `../../data/partitions-mock`: This is sample mock data where a sample of 1000 records is drawn from each of the 5 partitions. These records serve for only code testing purpose

## Steps Applied to convert WoS manual downloads to raw dataset
The raw dataset provided at `../../data/partitions` is passed through these step before creation of paritions.

### 1) Standardize columns: 
Only few selected columns are kept from the downloaded data to keep dataset managable

### 2) Deduplication: 
The data from WOS was downloaded manually in batches of different publication year. Naturally, many records may have been downloaded multiple times. Hence, deduplicaiton is performed using `UT (Unique WOS ID)` field as primary key of each record. All duplicate records are dropped

### 3) Drop records with missing abstracts:
Screening and coding decisions in the systematic map relies heavily on abstract text. For any record, where the abstract is missing, it is dropped.


For each of the step throughout this notebook, `*_metadata.json` is present that explains the outcomes of this notebook when ran last.

Lastly, it is not required to rerun this notebook. Both `../../data/partitions` and `../../data/partitions-mock` are provided as additional materials of this sytematic map. One may only downloaded and place these at correct paths. Notebook exists for reproducability should you need audit the steps.

In [1]:
from pathlib import Path
import re
import json
import tiktoken
from collections import Counter

import pandas as pd
import numpy as np

load_dir = Path('../../data/wos')
output_dir = Path('../../data/partitions')
output_dir_mock = Path('../../data/partitions-mock')

partition_size = 10000        
partition_size_mock = 1000      # For testing purposes, we can use smaller partitions
KEEP_COLUMNS = [
    'Publication Type',
    'Authors',
    'Article Title',
    'Language',
    'Document Type',
    'Author Keywords',
    'Keywords Plus',
    'Abstract',
    'Publisher',
    'Journal Abbreviation',
    'Journal ISO Abbreviation',
    'Publication Date',
    'Publication Year',
    'DOI',
    'DOI Link',
    'WoS Categories',
    'Web of Science Index',
    'Research Areas',
    'Pubmed Id',
    'UT (Unique WOS ID)',
]
output_dir.mkdir(parents=True, exist_ok=True)
output_dir_mock.mkdir(parents=True, exist_ok=True)
summary = {}

print(f'Load directory: {load_dir.resolve()}')
print(f'Output directory: {output_dir.resolve()}')
print(f'Mock output directory: {output_dir_mock.resolve()}')
print(f'Partition size: {partition_size:,} rows per file')
print(f'Mock partition size: {partition_size_mock:,} rows per file')
print(f'Keeping {len(KEEP_COLUMNS)} columns and dropping the rest')

Load directory: /Users/hunain/d/coding-projects/biodiversity/data/wos
Output directory: /Users/hunain/d/coding-projects/biodiversity/data/partitions
Mock output directory: /Users/hunain/d/coding-projects/biodiversity/data/partitions-mock
Partition size: 10,000 rows per file
Mock partition size: 1,000 rows per file
Keeping 20 columns and dropping the rest

In [2]:
files = sorted(load_dir.rglob('*.xls'))
summary['total_files'] = len(files)
print(f'Found {len(files)} .xls files under {load_dir}')
if not files:
    raise FileNotFoundError('No .xls files were found in ../../data/wos')

print('Sample files (first 10):')
for path in files[:10]:
    print(f' - {path}')

Found 2876 .xls files under ../../data/wos
Sample files (first 10):
 - ../../data/wos/2000/savedrecs (1).xls
 - ../../data/wos/2000/savedrecs (10).xls
 - ../../data/wos/2000/savedrecs (11).xls
 - ../../data/wos/2000/savedrecs (12).xls
 - ../../data/wos/2000/savedrecs (13).xls
 - ../../data/wos/2000/savedrecs (14).xls
 - ../../data/wos/2000/savedrecs (15).xls
 - ../../data/wos/2000/savedrecs (16).xls
 - ../../data/wos/2000/savedrecs (17).xls
 - ../../data/wos/2000/savedrecs (18).xls

In [3]:
preferred_engine = 'calamine'  # fastest for .xls if installed
engines_to_try = [preferred_engine, None, 'openpyxl', 'xlrd']

def load_with_fallback(path):
    errors = []
    for engine in engines_to_try:
        kwargs = {} if engine is None else {'engine': engine}
        engine_name = engine or 'auto'
        try:
            df = pd.read_excel(path, **kwargs)
            return df, engine_name
        except Exception as exc:
            errors.append(f"{engine_name}: {exc}")
    raise RuntimeError('; '.join(errors))

loaded_frames = []
failed_files = []
column_signatures = Counter()

for path in files:
    try:
        frame, engine_used = load_with_fallback(path)
        column_signatures[tuple(frame.columns)] += 1
        frame = frame.reindex(columns=KEEP_COLUMNS)
        loaded_frames.append(frame)
    except Exception as exc:
        failed_files.append((path, str(exc)))

summary['loaded_files'] = len(loaded_frames)
summary['failed_files'] = len(failed_files)

print(f"Files attempted: {len(files)} | Loaded: {summary['loaded_files']} | Failed: {summary['failed_files']}")
if failed_files:
    print('Failed files (path and last error):')
    for path, err in failed_files:
        print(f' - {path}: {err}')

Files attempted: 2876 | Loaded: 2876 | Failed: 0

In [4]:
if not loaded_frames:
    raise RuntimeError('No data frames were loaded; please resolve the load errors above.')

print(f'Unique column signatures (ordered): {len(column_signatures)}')
for cols, count in column_signatures.most_common():
    print(f' - {count} file(s): {len(cols)} columns')
    print(f"   Columns: {', '.join(cols)}")

most_common_cols = list(column_signatures.most_common(1)[0][0])
if len(column_signatures) > 1:
    print('Column differences relative to the most common signature:')
    base_set = set(most_common_cols)
    for cols, count in column_signatures.items():
        col_set = set(cols)
        missing = sorted(base_set - col_set)
        extra = sorted(col_set - base_set)
        if missing or extra:
            print(f" - {count} file(s): missing={missing or 'None'}, extra={extra or 'None'}")
else:
    print('All files share the same column order.')

aligned_frames = [frame.reindex(columns=KEEP_COLUMNS) for frame in loaded_frames]
print(f'Aligned all frames to {len(KEEP_COLUMNS)} kept columns.')

Unique column signatures (ordered): 1
 - 2876 file(s): 72 columns
   Columns: Publication Type, Authors, Book Authors, Book Editors, Book Group Authors, Author Full Names, Book Author Full Names, Group Authors, Article Title, Source Title, Book Series Title, Book Series Subtitle, Language, Document Type, Conference Title, Conference Date, Conference Location, Conference Sponsor, Conference Host, Author Keywords, Keywords Plus, Abstract, Addresses, Affiliations, Reprint Addresses, Email Addresses, Researcher Ids, ORCIDs, Funding Orgs, Funding Name Preferred, Funding Text, Cited References, Cited Reference Count, Times Cited, WoS Core, Times Cited, All Databases, 180 Day Usage Count, Since 2013 Usage Count, Publisher, Publisher City, Publisher Address, ISSN, eISSN, ISBN, Journal Abbreviation, Journal ISO Abbreviation, Publication Date, Publication Year, Volume, Issue, Part Number, Supplement, Special Issue, Meeting Abstract, Start Page, End Page, Article Number, DOI, DOI Link, Book DOI, Early Access Date, Number of Pages, WoS Categories, Web of Science Index, Research Areas, IDS Number, Pubmed Id, Open Access Designations, Highly Cited Status, Hot Paper Status, Date of Export, UT (Unique WOS ID), Web of Science Record
All files share the same column order.
Aligned all frames to 20 kept columns.

In [5]:
combined = pd.concat(aligned_frames, ignore_index=True)
required_columns = ['Article Title', 'Abstract', 'Publication Year', 'UT (Unique WOS ID)']
missing_required = [col for col in required_columns if col not in combined.columns]
if missing_required:
    raise KeyError(f'Missing required columns: {missing_required}')

summary['rows_before_dedup'] = len(combined)
duplicate_rows = int(combined.duplicated(subset=['UT (Unique WOS ID)']).sum())
summary['duplicate_rows'] = duplicate_rows
print(f"Combined rows (before dedup): {summary['rows_before_dedup']:,}")
print(f"Duplicate rows detected (by UT): {duplicate_rows:,}")

combined = combined.drop_duplicates(subset=['UT (Unique WOS ID)']).reset_index(drop=True)
summary['rows_after_dedup'] = len(combined)
print(f"Rows after removing UT-duplicates: {summary['rows_after_dedup']:,}")

Combined rows (before dedup): 2,861,929
Duplicate rows detected (by UT): 435,121
Rows after removing UT-duplicates: 2,426,808

In [6]:
abstract_series = combined['Abstract']
abstract_missing = abstract_series.isna() | abstract_series.astype(str).str.strip().eq('')
abstract_missing_count = int(abstract_missing.sum())
summary['abstract_null_or_empty'] = abstract_missing_count
print(f"Rows with null/empty abstracts: {abstract_missing_count:,}")

combined = combined.loc[~abstract_missing].copy()
summary['rows_after_abstract_filter'] = len(combined)
print(f"Rows after dropping null/empty abstracts: {summary['rows_after_abstract_filter']:,}")

Rows with null/empty abstracts: 12,617
Rows after dropping null/empty abstracts: 2,414,191

In [7]:
combined['Publication Year'] = pd.to_numeric(combined['Publication Year'], errors='coerce')
publication_year_missing = int(combined['Publication Year'].isna().sum())
summary['publication_year_missing'] = publication_year_missing
combined['UT (Unique WOS ID)'] = combined['UT (Unique WOS ID)'].fillna('').astype(str)
combined = combined.sort_values(by=['Publication Year', 'UT (Unique WOS ID)'], ascending=[False, True]).reset_index(drop=True)
summary['final_rows'] = len(combined)
print(f"Rows ready for export: {summary['final_rows']:,}")
print(f"Rows with missing publication year (sorted to bottom): {publication_year_missing:,}")

Rows ready for export: 2,414,191
Rows with missing publication year (sorted to bottom): 0

In [8]:
summary_table = pd.DataFrame([
    ('Total Excel files', summary.get('total_files', 0)),
    ('Files loaded', summary.get('loaded_files', 0)),
    ('Files failed', summary.get('failed_files', 0)),
    ('Rows before dedup', summary.get('rows_before_dedup', 0)),
    ('Duplicate rows', summary.get('duplicate_rows', 0)),
    ('Rows after dedup', summary.get('rows_after_dedup', 0)),
    ('Abstract null/empty', summary.get('abstract_null_or_empty', 0)),
    ('Rows after abstract filter', summary.get('rows_after_abstract_filter', 0)),
    ('Publication year missing', summary.get('publication_year_missing', 0)),
    ('Final rows', summary.get('final_rows', 0)),
])
summary_table.columns = ['Metric', 'Count']
summary_table

                       Metric    Count
0           Total Excel files     2876
1                Files loaded     2876
2                Files failed        0
3           Rows before dedup  2861929
4              Duplicate rows   435121
5            Rows after dedup  2426808
6         Abstract null/empty    12617
7  Rows after abstract filter  2414191
8    Publication year missing        0
9                  Final rows  2414191

In [9]:
encoding = tiktoken.get_encoding('cl100k_base')
encode = encoding.encode_ordinary
text_series = combined[['Article Title', 'Abstract']].fillna('').astype(str).agg(' '.join, axis=1)
token_counts = pd.Series(np.fromiter((len(encode(t)) for t in text_series), dtype=np.int64))
token_stats = {
    'sum_tokens': int(token_counts.sum()),
    'avg_per_row': float(token_counts.mean()),
    'median_per_row': float(token_counts.median()),
    'percentile_25': float(token_counts.quantile(0.25)),
    'percentile_75': float(token_counts.quantile(0.75)),
}
token_stats_df = pd.DataFrame(list(token_stats.items()), columns=['Metric', 'Value'])
token_stats_df

           Metric         Value
0      sum_tokens  8.395938e+08
1     avg_per_row  3.477744e+02
2  median_per_row  3.370000e+02
3   percentile_25  2.760000e+02
4   percentile_75  4.040000e+02

In [10]:
full_export_path = output_dir / 'wos_all.csv'
combined.to_csv(full_export_path, index=False)
print(f"Saved full combined dataset ({len(combined):,} rows) -> {full_export_path}")

Saved full combined dataset (2,414,191 rows) -> ../../data/partitions/wos_all.csv

In [11]:
if combined.empty:
    print('No rows to partition; nothing written.')
else:
    num_partitions = int(np.ceil(len(combined) / partition_size))
    pad_width = max(2, len(str(num_partitions)))
    saved_files = []
    saved_mock_files = []
    partition_meta = []
    partition_meta_mock = []
    for idx in range(num_partitions):
        start = idx * partition_size
        end = start + partition_size
        chunk = combined.iloc[start:end]
        chunk_token_counts = token_counts.iloc[start:end]
        partition_id = str(idx + 1)
        year_series = pd.to_numeric(chunk['Publication Year'], errors='coerce')
        year_valid = year_series.dropna()
        min_year = int(year_valid.min()) if not year_valid.empty else 'na'
        max_year = int(year_valid.max()) if not year_valid.empty else 'na'
        fname = f"wos_{str(idx + 1).zfill(pad_width)}_{max_year}-{min_year}.xlsx"

        subdir = output_dir / partition_id
        subdir.mkdir(parents=True, exist_ok=True)
        filename = subdir / fname
        chunk.to_excel(filename, index=False)
        chunk_token_sum = int(chunk_token_counts.sum())
        partition_meta.append({
            'partition': idx + 1,
            'file': str(filename),
            'rows': int(len(chunk)),
            'token_sum': chunk_token_sum,
            'min_year': min_year,
            'max_year': max_year,
        })
        saved_files.append(filename)
        print(f"Saved partition {idx + 1} with {len(chunk):,} rows -> {filename} | tokens: {chunk_token_sum:,}")

        mock_subdir = output_dir_mock / partition_id
        mock_subdir.mkdir(parents=True, exist_ok=True)
        mock_sample_size = min(partition_size_mock, len(chunk))
        mock_chunk = chunk.sample(n=mock_sample_size, random_state=idx).sort_index()
        mock_token_sum = int(token_counts.loc[mock_chunk.index].sum())
        mock_filename = mock_subdir / fname
        mock_chunk.to_excel(mock_filename, index=False)
        partition_meta_mock.append({
            'partition': idx + 1,
            'source_partition_file': str(filename),
            'file': str(mock_filename),
            'rows': int(len(mock_chunk)),
            'token_sum': mock_token_sum,
            'sample_size_requested': int(partition_size_mock),
            'min_year': min_year,
            'max_year': max_year,
        })
        saved_mock_files.append(mock_filename)
        print(f"Saved mock partition {idx + 1} with {len(mock_chunk):,} rows -> {mock_filename} | tokens: {mock_token_sum:,}")

    summary_table_records = summary_table.to_dict(orient='records')
    metadata_payload = {
        'summary_table': summary_table_records,
        'partitions': partition_meta,
    }
    metadata_path = output_dir / 'partition_token_metadata.json'
    metadata_path.write_text(json.dumps(metadata_payload, indent=2))
    metadata_payload_mock = {
        'summary_table': summary_table_records,
        'partitions': partition_meta_mock,
    }
    metadata_path_mock = output_dir_mock / 'partition_token_metadata.json'
    metadata_path_mock.write_text(json.dumps(metadata_payload_mock, indent=2))
    print(f"Completed writing {len(saved_files)} partition file(s).")
    print(f"Partition token metadata written to {metadata_path}")
    print(f"Completed writing {len(saved_mock_files)} mock partition file(s).")
    print(f"Mock partition token metadata written to {metadata_path_mock}")

Saved partition 1 with 10,000 rows -> ../../data/partitions/1/wos_001_2026-2026.xlsx | tokens: 3,643,678
Saved mock partition 1 with 1,000 rows -> ../../data/partitions-mock/1/wos_001_2026-2026.xlsx | tokens: 363,939
Saved partition 2 with 10,000 rows -> ../../data/partitions/2/wos_002_2026-2026.xlsx | tokens: 3,640,124
Saved mock partition 2 with 1,000 rows -> ../../data/partitions-mock/2/wos_002_2026-2026.xlsx | tokens: 362,473
Saved partition 3 with 10,000 rows -> ../../data/partitions/3/wos_003_2026-2026.xlsx | tokens: 3,652,378
Saved mock partition 3 with 1,000 rows -> ../../data/partitions-mock/3/wos_003_2026-2026.xlsx | tokens: 363,065
Saved partition 4 with 10,000 rows -> ../../data/partitions/4/wos_004_2026-2026.xlsx | tokens: 3,644,995
Saved mock partition 4 with 1,000 rows -> ../../data/partitions-mock/4/wos_004_2026-2026.xlsx | tokens: 362,797
Saved partition 5 with 10,000 rows -> ../../data/partitions/5/wos_005_2026-2026.xlsx | tokens: 3,631,502
Saved mock partition 5 with 1,000 rows -> ../../data/partitions-mock/5/wos_005_2026-2026.xlsx | tokens: 364,465
Saved partition 6 with 10,000 rows -> ../../data/partitions/6/wos_006_2026-2026.xlsx | tokens: 3,669,909
Saved mock partition 6 with 1,000 rows -> ../../data/partitions-mock/6/wos_006_2026-2026.xlsx | tokens: 365,554
Saved partition 7 with 10,000 rows -> ../../data/partitions/7/wos_007_2026-2026.xlsx | tokens: 3,632,922
Saved mock partition 7 with 1,000 rows -> ../../data/partitions-mock/7/wos_007_2026-2026.xlsx | tokens: 358,777
Saved partition 8 with 10,000 rows -> ../../data/partitions/8/wos_008_2026-2026.xlsx | tokens: 3,674,483
Saved mock partition 8 with 1,000 rows -> ../../data/partitions-mock/8/wos_008_2026-2026.xlsx | tokens: 367,554
Saved partition 9 with 10,000 rows -> ../../data/partitions/9/wos_009_2026-2025.xlsx | tokens: 3,581,996
Saved mock partition 9 with 1,000 rows -> ../../data/partitions-mock/9/wos_009_2026-2025.xlsx | tokens: 351,234
Saved partition 10 with 10,000 rows -> ../../data/partitions/10/wos_010_2025-2025.xlsx | tokens: 3,622,150
Saved mock partition 10 with 1,000 rows -> ../../data/partitions-mock/10/wos_010_2025-2025.xlsx | tokens: 368,203
Saved partition 11 with 10,000 rows -> ../../data/partitions/11/wos_011_2025-2025.xlsx | tokens: 3,585,441
Saved mock partition 11 with 1,000 rows -> ../../data/partitions-mock/11/wos_011_2025-2025.xlsx | tokens: 358,451
Saved partition 12 with 10,000 rows -> ../../data/partitions/12/wos_012_2025-2025.xlsx | tokens: 3,569,741
Saved mock partition 12 with 1,000 rows -> ../../data/partitions-mock/12/wos_012_2025-2025.xlsx | tokens: 355,922
Saved partition 13 with 10,000 rows -> ../../data/partitions/13/wos_013_2025-2025.xlsx | tokens: 3,587,509
Saved mock partition 13 with 1,000 rows -> ../../data/partitions-mock/13/wos_013_2025-2025.xlsx | tokens: 358,681
Saved partition 14 with 10,000 rows -> ../../data/partitions/14/wos_014_2025-2025.xlsx | tokens: 3,578,435
Saved mock partition 14 with 1,000 rows -> ../../data/partitions-mock/14/wos_014_2025-2025.xlsx | tokens: 352,371
Saved partition 15 with 10,000 rows -> ../../data/partitions/15/wos_015_2025-2025.xlsx | tokens: 3,559,227
Saved mock partition 15 with 1,000 rows -> ../../data/partitions-mock/15/wos_015_2025-2025.xlsx | tokens: 352,427
Saved partition 16 with 10,000 rows -> ../../data/partitions/16/wos_016_2025-2025.xlsx | tokens: 3,600,106
Saved mock partition 16 with 1,000 rows -> ../../data/partitions-mock/16/wos_016_2025-2025.xlsx | tokens: 354,963
Saved partition 17 with 10,000 rows -> ../../data/partitions/17/wos_017_2025-2025.xlsx | tokens: 3,588,148
Saved mock partition 17 with 1,000 rows -> ../../data/partitions-mock/17/wos_017_2025-2025.xlsx | tokens: 359,197
Saved partition 18 with 10,000 rows -> ../../data/partitions/18/wos_018_2025-2025.xlsx | tokens: 3,589,574
Saved mock partition 18 with 1,000 rows -> ../../data/partitions-mock/18/wos_018_2025-2025.xlsx | tokens: 360,617
Saved partition 19 with 10,000 rows -> ../../data/partitions/19/wos_019_2025-2025.xlsx | tokens: 3,627,752
Saved mock partition 19 with 1,000 rows -> ../../data/partitions-mock/19/wos_019_2025-2025.xlsx | tokens: 359,761
Saved partition 20 with 10,000 rows -> ../../data/partitions/20/wos_020_2025-2025.xlsx | tokens: 3,555,073
Saved mock partition 20 with 1,000 rows -> ../../data/partitions-mock/20/wos_020_2025-2025.xlsx | tokens: 347,934
Saved partition 21 with 10,000 rows -> ../../data/partitions/21/wos_021_2025-2025.xlsx | tokens: 3,574,736
Saved mock partition 21 with 1,000 rows -> ../../data/partitions-mock/21/wos_021_2025-2025.xlsx | tokens: 355,483
Saved partition 22 with 10,000 rows -> ../../data/partitions/22/wos_022_2025-2025.xlsx | tokens: 3,619,720
Saved mock partition 22 with 1,000 rows -> ../../data/partitions-mock/22/wos_022_2025-2025.xlsx | tokens: 363,011
Saved partition 23 with 10,000 rows -> ../../data/partitions/23/wos_023_2025-2025.xlsx | tokens: 3,596,465
Saved mock partition 23 with 1,000 rows -> ../../data/partitions-mock/23/wos_023_2025-2025.xlsx | tokens: 362,805
Saved partition 24 with 10,000 rows -> ../../data/partitions/24/wos_024_2025-2025.xlsx | tokens: 3,605,958
Saved mock partition 24 with 1,000 rows -> ../../data/partitions-mock/24/wos_024_2025-2025.xlsx | tokens: 359,836
Saved partition 25 with 10,000 rows -> ../../data/partitions/25/wos_025_2025-2025.xlsx | tokens: 3,590,245
Saved mock partition 25 with 1,000 rows -> ../../data/partitions-mock/25/wos_025_2025-2025.xlsx | tokens: 359,121
Saved partition 26 with 10,000 rows -> ../../data/partitions/26/wos_026_2025-2025.xlsx | tokens: 3,619,070
Saved mock partition 26 with 1,000 rows -> ../../data/partitions-mock/26/wos_026_2025-2025.xlsx | tokens: 367,321
Saved partition 27 with 10,000 rows -> ../../data/partitions/27/wos_027_2025-2025.xlsx | tokens: 3,578,859
Saved mock partition 27 with 1,000 rows -> ../../data/partitions-mock/27/wos_027_2025-2025.xlsx | tokens: 355,003
Saved partition 28 with 10,000 rows -> ../../data/partitions/28/wos_028_2025-2025.xlsx | tokens: 3,632,013
Saved mock partition 28 with 1,000 rows -> ../../data/partitions-mock/28/wos_028_2025-2025.xlsx | tokens: 367,782
Saved partition 29 with 10,000 rows -> ../../data/partitions/29/wos_029_2025-2024.xlsx | tokens: 3,525,008
Saved mock partition 29 with 1,000 rows -> ../../data/partitions-mock/29/wos_029_2025-2024.xlsx | tokens: 353,084
Saved partition 30 with 10,000 rows -> ../../data/partitions/30/wos_030_2024-2024.xlsx | tokens: 3,658,552
Saved mock partition 30 with 1,000 rows -> ../../data/partitions-mock/30/wos_030_2024-2024.xlsx | tokens: 368,737
Saved partition 31 with 10,000 rows -> ../../data/partitions/31/wos_031_2024-2024.xlsx | tokens: 3,671,863
Saved mock partition 31 with 1,000 rows -> ../../data/partitions-mock/31/wos_031_2024-2024.xlsx | tokens: 363,962
Saved partition 32 with 10,000 rows -> ../../data/partitions/32/wos_032_2024-2024.xlsx | tokens: 3,671,438
Saved mock partition 32 with 1,000 rows -> ../../data/partitions-mock/32/wos_032_2024-2024.xlsx | tokens: 365,536
Saved partition 33 with 10,000 rows -> ../../data/partitions/33/wos_033_2024-2024.xlsx | tokens: 3,678,775
Saved mock partition 33 with 1,000 rows -> ../../data/partitions-mock/33/wos_033_2024-2024.xlsx | tokens: 367,619
Saved partition 34 with 10,000 rows -> ../../data/partitions/34/wos_034_2024-2024.xlsx | tokens: 3,677,829
Saved mock partition 34 with 1,000 rows -> ../../data/partitions-mock/34/wos_034_2024-2024.xlsx | tokens: 368,263
Saved partition 35 with 10,000 rows -> ../../data/partitions/35/wos_035_2024-2024.xlsx | tokens: 3,699,771
Saved mock partition 35 with 1,000 rows -> ../../data/partitions-mock/35/wos_035_2024-2024.xlsx | tokens: 370,063
Saved partition 36 with 10,000 rows -> ../../data/partitions/36/wos_036_2024-2024.xlsx | tokens: 3,706,903
Saved mock partition 36 with 1,000 rows -> ../../data/partitions-mock/36/wos_036_2024-2024.xlsx | tokens: 373,854
Saved partition 37 with 10,000 rows -> ../../data/partitions/37/wos_037_2024-2024.xlsx | tokens: 3,658,876
Saved mock partition 37 with 1,000 rows -> ../../data/partitions-mock/37/wos_037_2024-2024.xlsx | tokens: 367,025
Saved partition 38 with 10,000 rows -> ../../data/partitions/38/wos_038_2024-2024.xlsx | tokens: 3,676,255
Saved mock partition 38 with 1,000 rows -> ../../data/partitions-mock/38/wos_038_2024-2024.xlsx | tokens: 362,104
Saved partition 39 with 10,000 rows -> ../../data/partitions/39/wos_039_2024-2024.xlsx | tokens: 3,692,965
Saved mock partition 39 with 1,000 rows -> ../../data/partitions-mock/39/wos_039_2024-2024.xlsx | tokens: 373,383
Saved partition 40 with 10,000 rows -> ../../data/partitions/40/wos_040_2024-2024.xlsx | tokens: 3,721,915
Saved mock partition 40 with 1,000 rows -> ../../data/partitions-mock/40/wos_040_2024-2024.xlsx | tokens: 379,446
Saved partition 41 with 10,000 rows -> ../../data/partitions/41/wos_041_2024-2024.xlsx | tokens: 3,670,218
Saved mock partition 41 with 1,000 rows -> ../../data/partitions-mock/41/wos_041_2024-2024.xlsx | tokens: 369,104
Saved partition 42 with 10,000 rows -> ../../data/partitions/42/wos_042_2024-2024.xlsx | tokens: 3,693,604
Saved mock partition 42 with 1,000 rows -> ../../data/partitions-mock/42/wos_042_2024-2024.xlsx | tokens: 370,784
Saved partition 43 with 10,000 rows -> ../../data/partitions/43/wos_043_2024-2024.xlsx | tokens: 3,666,998
Saved mock partition 43 with 1,000 rows -> ../../data/partitions-mock/43/wos_043_2024-2024.xlsx | tokens: 369,732
Saved partition 44 with 10,000 rows -> ../../data/partitions/44/wos_044_2024-2024.xlsx | tokens: 3,640,552
Saved mock partition 44 with 1,000 rows -> ../../data/partitions-mock/44/wos_044_2024-2024.xlsx | tokens: 365,934
Saved partition 45 with 10,000 rows -> ../../data/partitions/45/wos_045_2024-2024.xlsx | tokens: 3,702,687
Saved mock partition 45 with 1,000 rows -> ../../data/partitions-mock/45/wos_045_2024-2024.xlsx | tokens: 371,976
Saved partition 46 with 10,000 rows -> ../../data/partitions/46/wos_046_2024-2024.xlsx | tokens: 3,585,872
Saved mock partition 46 with 1,000 rows -> ../../data/partitions-mock/46/wos_046_2024-2024.xlsx | tokens: 355,245
Saved partition 47 with 10,000 rows -> ../../data/partitions/47/wos_047_2024-2024.xlsx | tokens: 3,566,934
Saved mock partition 47 with 1,000 rows -> ../../data/partitions-mock/47/wos_047_2024-2024.xlsx | tokens: 353,632
Saved partition 48 with 10,000 rows -> ../../data/partitions/48/wos_048_2024-2024.xlsx | tokens: 3,522,063
Saved mock partition 48 with 1,000 rows -> ../../data/partitions-mock/48/wos_048_2024-2024.xlsx | tokens: 350,947
Saved partition 49 with 10,000 rows -> ../../data/partitions/49/wos_049_2024-2023.xlsx | tokens: 3,412,121
Saved mock partition 49 with 1,000 rows -> ../../data/partitions-mock/49/wos_049_2024-2023.xlsx | tokens: 344,234
Saved partition 50 with 10,000 rows -> ../../data/partitions/50/wos_050_2023-2023.xlsx | tokens: 3,591,604
Saved mock partition 50 with 1,000 rows -> ../../data/partitions-mock/50/wos_050_2023-2023.xlsx | tokens: 363,323
Saved partition 51 with 10,000 rows -> ../../data/partitions/51/wos_051_2023-2023.xlsx | tokens: 3,618,428
Saved mock partition 51 with 1,000 rows -> ../../data/partitions-mock/51/wos_051_2023-2023.xlsx | tokens: 356,806
Saved partition 52 with 10,000 rows -> ../../data/partitions/52/wos_052_2023-2023.xlsx | tokens: 3,618,784
Saved mock partition 52 with 1,000 rows -> ../../data/partitions-mock/52/wos_052_2023-2023.xlsx | tokens: 357,100
Saved partition 53 with 10,000 rows -> ../../data/partitions/53/wos_053_2023-2023.xlsx | tokens: 3,619,864
Saved mock partition 53 with 1,000 rows -> ../../data/partitions-mock/53/wos_053_2023-2023.xlsx | tokens: 355,459
Saved partition 54 with 10,000 rows -> ../../data/partitions/54/wos_054_2023-2023.xlsx | tokens: 3,609,600
Saved mock partition 54 with 1,000 rows -> ../../data/partitions-mock/54/wos_054_2023-2023.xlsx | tokens: 356,480
Saved partition 55 with 10,000 rows -> ../../data/partitions/55/wos_055_2023-2023.xlsx | tokens: 3,604,784
Saved mock partition 55 with 1,000 rows -> ../../data/partitions-mock/55/wos_055_2023-2023.xlsx | tokens: 357,707
Saved partition 56 with 10,000 rows -> ../../data/partitions/56/wos_056_2023-2023.xlsx | tokens: 3,571,522
Saved mock partition 56 with 1,000 rows -> ../../data/partitions-mock/56/wos_056_2023-2023.xlsx | tokens: 361,492
Saved partition 57 with 10,000 rows -> ../../data/partitions/57/wos_057_2023-2023.xlsx | tokens: 3,593,322
Saved mock partition 57 with 1,000 rows -> ../../data/partitions-mock/57/wos_057_2023-2023.xlsx | tokens: 359,564
Saved partition 58 with 10,000 rows -> ../../data/partitions/58/wos_058_2023-2023.xlsx | tokens: 3,599,087
Saved mock partition 58 with 1,000 rows -> ../../data/partitions-mock/58/wos_058_2023-2023.xlsx | tokens: 362,870
Saved partition 59 with 10,000 rows -> ../../data/partitions/59/wos_059_2023-2023.xlsx | tokens: 3,627,669
Saved mock partition 59 with 1,000 rows -> ../../data/partitions-mock/59/wos_059_2023-2023.xlsx | tokens: 365,448
Saved partition 60 with 10,000 rows -> ../../data/partitions/60/wos_060_2023-2023.xlsx | tokens: 3,621,221
Saved mock partition 60 with 1,000 rows -> ../../data/partitions-mock/60/wos_060_2023-2023.xlsx | tokens: 355,114
Saved partition 61 with 10,000 rows -> ../../data/partitions/61/wos_061_2023-2023.xlsx | tokens: 3,623,753
Saved mock partition 61 with 1,000 rows -> ../../data/partitions-mock/61/wos_061_2023-2023.xlsx | tokens: 364,059
Saved partition 62 with 10,000 rows -> ../../data/partitions/62/wos_062_2023-2023.xlsx | tokens: 3,638,911
Saved mock partition 62 with 1,000 rows -> ../../data/partitions-mock/62/wos_062_2023-2023.xlsx | tokens: 366,187
Saved partition 63 with 10,000 rows -> ../../data/partitions/63/wos_063_2023-2023.xlsx | tokens: 3,578,734
Saved mock partition 63 with 1,000 rows -> ../../data/partitions-mock/63/wos_063_2023-2023.xlsx | tokens: 360,412
Saved partition 64 with 10,000 rows -> ../../data/partitions/64/wos_064_2023-2023.xlsx | tokens: 3,558,454
Saved mock partition 64 with 1,000 rows -> ../../data/partitions-mock/64/wos_064_2023-2023.xlsx | tokens: 354,475
Saved partition 65 with 10,000 rows -> ../../data/partitions/65/wos_065_2023-2023.xlsx | tokens: 3,638,063
Saved mock partition 65 with 1,000 rows -> ../../data/partitions-mock/65/wos_065_2023-2023.xlsx | tokens: 364,057
Saved partition 66 with 10,000 rows -> ../../data/partitions/66/wos_066_2023-2023.xlsx | tokens: 3,610,191
Saved mock partition 66 with 1,000 rows -> ../../data/partitions-mock/66/wos_066_2023-2023.xlsx | tokens: 365,094
Saved partition 67 with 10,000 rows -> ../../data/partitions/67/wos_067_2023-2022.xlsx | tokens: 3,338,199
Saved mock partition 67 with 1,000 rows -> ../../data/partitions-mock/67/wos_067_2023-2022.xlsx | tokens: 333,830
Saved partition 68 with 10,000 rows -> ../../data/partitions/68/wos_068_2022-2022.xlsx | tokens: 3,565,645
Saved mock partition 68 with 1,000 rows -> ../../data/partitions-mock/68/wos_068_2022-2022.xlsx | tokens: 360,147
Saved partition 69 with 10,000 rows -> ../../data/partitions/69/wos_069_2022-2022.xlsx | tokens: 3,534,960
Saved mock partition 69 with 1,000 rows -> ../../data/partitions-mock/69/wos_069_2022-2022.xlsx | tokens: 350,302
Saved partition 70 with 10,000 rows -> ../../data/partitions/70/wos_070_2022-2022.xlsx | tokens: 3,521,185
Saved mock partition 70 with 1,000 rows -> ../../data/partitions-mock/70/wos_070_2022-2022.xlsx | tokens: 352,479
Saved partition 71 with 10,000 rows -> ../../data/partitions/71/wos_071_2022-2022.xlsx | tokens: 3,571,795
Saved mock partition 71 with 1,000 rows -> ../../data/partitions-mock/71/wos_071_2022-2022.xlsx | tokens: 359,929
Saved partition 72 with 10,000 rows -> ../../data/partitions/72/wos_072_2022-2022.xlsx | tokens: 3,491,962
Saved mock partition 72 with 1,000 rows -> ../../data/partitions-mock/72/wos_072_2022-2022.xlsx | tokens: 347,183
Saved partition 73 with 10,000 rows -> ../../data/partitions/73/wos_073_2022-2022.xlsx | tokens: 3,512,546
Saved mock partition 73 with 1,000 rows -> ../../data/partitions-mock/73/wos_073_2022-2022.xlsx | tokens: 343,299
Saved partition 74 with 10,000 rows -> ../../data/partitions/74/wos_074_2022-2022.xlsx | tokens: 3,653,574
Saved mock partition 74 with 1,000 rows -> ../../data/partitions-mock/74/wos_074_2022-2022.xlsx | tokens: 361,589
Saved partition 75 with 10,000 rows -> ../../data/partitions/75/wos_075_2022-2022.xlsx | tokens: 3,560,136
Saved mock partition 75 with 1,000 rows -> ../../data/partitions-mock/75/wos_075_2022-2022.xlsx | tokens: 359,501
Saved partition 76 with 10,000 rows -> ../../data/partitions/76/wos_076_2022-2022.xlsx | tokens: 3,568,476
Saved mock partition 76 with 1,000 rows -> ../../data/partitions-mock/76/wos_076_2022-2022.xlsx | tokens: 356,759
Saved partition 77 with 10,000 rows -> ../../data/partitions/77/wos_077_2022-2022.xlsx | tokens: 3,561,829
Saved mock partition 77 with 1,000 rows -> ../../data/partitions-mock/77/wos_077_2022-2022.xlsx | tokens: 354,662
Saved partition 78 with 10,000 rows -> ../../data/partitions/78/wos_078_2022-2022.xlsx | tokens: 3,579,518
Saved mock partition 78 with 1,000 rows -> ../../data/partitions-mock/78/wos_078_2022-2022.xlsx | tokens: 358,686
Saved partition 79 with 10,000 rows -> ../../data/partitions/79/wos_079_2022-2022.xlsx | tokens: 3,563,688
Saved mock partition 79 with 1,000 rows -> ../../data/partitions-mock/79/wos_079_2022-2022.xlsx | tokens: 357,518
Saved partition 80 with 10,000 rows -> ../../data/partitions/80/wos_080_2022-2022.xlsx | tokens: 3,598,996
Saved mock partition 80 with 1,000 rows -> ../../data/partitions-mock/80/wos_080_2022-2022.xlsx | tokens: 358,765
Saved partition 81 with 10,000 rows -> ../../data/partitions/81/wos_081_2022-2022.xlsx | tokens: 3,635,290
Saved mock partition 81 with 1,000 rows -> ../../data/partitions-mock/81/wos_081_2022-2022.xlsx | tokens: 367,573
Saved partition 82 with 10,000 rows -> ../../data/partitions/82/wos_082_2022-2022.xlsx | tokens: 3,552,461
Saved mock partition 82 with 1,000 rows -> ../../data/partitions-mock/82/wos_082_2022-2022.xlsx | tokens: 349,866
Saved partition 83 with 10,000 rows -> ../../data/partitions/83/wos_083_2022-2022.xlsx | tokens: 3,565,025
Saved mock partition 83 with 1,000 rows -> ../../data/partitions-mock/83/wos_083_2022-2022.xlsx | tokens: 357,877
Saved partition 84 with 10,000 rows -> ../../data/partitions/84/wos_084_2022-2022.xlsx | tokens: 3,602,919
Saved mock partition 84 with 1,000 rows -> ../../data/partitions-mock/84/wos_084_2022-2022.xlsx | tokens: 359,762
Saved partition 85 with 10,000 rows -> ../../data/partitions/85/wos_085_2022-2021.xlsx | tokens: 3,401,942
Saved mock partition 85 with 1,000 rows -> ../../data/partitions-mock/85/wos_085_2022-2021.xlsx | tokens: 336,933
Saved partition 86 with 10,000 rows -> ../../data/partitions/86/wos_086_2021-2021.xlsx | tokens: 3,545,632
Saved mock partition 86 with 1,000 rows -> ../../data/partitions-mock/86/wos_086_2021-2021.xlsx | tokens: 356,039
Saved partition 87 with 10,000 rows -> ../../data/partitions/87/wos_087_2021-2021.xlsx | tokens: 3,631,664
Saved mock partition 87 with 1,000 rows -> ../../data/partitions-mock/87/wos_087_2021-2021.xlsx | tokens: 363,503
Saved partition 88 with 10,000 rows -> ../../data/partitions/88/wos_088_2021-2021.xlsx | tokens: 3,578,295
Saved mock partition 88 with 1,000 rows -> ../../data/partitions-mock/88/wos_088_2021-2021.xlsx | tokens: 359,455
Saved partition 89 with 10,000 rows -> ../../data/partitions/89/wos_089_2021-2021.xlsx | tokens: 3,562,086
Saved mock partition 89 with 1,000 rows -> ../../data/partitions-mock/89/wos_089_2021-2021.xlsx | tokens: 356,951
Saved partition 90 with 10,000 rows -> ../../data/partitions/90/wos_090_2021-2021.xlsx | tokens: 3,555,718
Saved mock partition 90 with 1,000 rows -> ../../data/partitions-mock/90/wos_090_2021-2021.xlsx | tokens: 358,179
Saved partition 91 with 10,000 rows -> ../../data/partitions/91/wos_091_2021-2021.xlsx | tokens: 3,614,735